// import PDFDocument from "pdfkit";
// import fs from "fs";
// import path from "path";

// export default function generatePDF(app){

//  return new Promise(resolve=>{

//   const filePath=`uploads/${app._id}.pdf`; // remove this
// //   cloudinray 
//   const doc=new PDFDocument();

//   doc.pipe(fs.createWriteStream(filePath));

//   doc.fontSize(20).text("APPLICATION DETAILS",{align:"center"});
//   doc.moveDown();

//   doc.fontSize(12).text(`Name: ${app.userDetails.name}`);
//   doc.text(`Email: ${app.userDetails.email}`);
//   doc.text(`Phone: ${app.userDetails.phone}`);
//   doc.text(`Service: ${app.serviceName}`);
//   doc.text(`Status: ${app.status}`);

//   doc.moveDown();
//   doc.text("Documents:");

//   app.uploadedDocuments.forEach(d=>{
//    doc.text("• "+d.documentName);
//   });

//   doc.end();

//   resolve(filePath);
//  });
// }


// ******************

// import PDFDocument from "pdfkit";
// import axios from "axios";
// import QRCode from "qrcode";

// export default async function generatePDFBuffer(app) {
//   return new Promise(async (resolve, reject) => {
//     try {
//       const doc = new PDFDocument({ margin: 40 });
//       const buffers = [];

//       doc.on("data", buffers.push.bind(buffers));
//       doc.on("end", () => resolve(Buffer.concat(buffers)));

//       /* HEADER */
//       doc.rect(0, 0, doc.page.width, 70).fill("#1e3a8a");
//       doc.fillColor("white").fontSize(22).text("APPLICATION REPORT", 40, 25);
//       doc.fontSize(11).text("CADMA Associates Pvt Ltd", 40, 50);

//       doc.moveDown(3);
//       doc.fillColor("black");

//       /* DETAILS */
//       doc.fontSize(16).text("Applicant Details", { underline: true });
//       doc.moveDown();

//       const info = [
//         ["Name", app.userDetails?.name],
//         ["Email", app.userDetails?.email],
//         ["Phone", app.userDetails?.phone],
//         ["Service", app.serviceName],
//         ["Status", app.status],
//         ["Application ID", app._id],
//       ];

//       info.forEach(([k, v]) => {
//         doc.font("Helvetica-Bold").text(`${k}: `, { continued: true });
//         doc.font("Helvetica").text(v || "-");
//       });

//       doc.moveDown(2);

//       /* DOCUMENTS */
//       doc.fontSize(16).text("Uploaded Documents", { underline: true });
//       doc.moveDown();

//       for (const file of app.uploadedDocuments || []) {
//         const url = file.fileURL;

//         doc
//           .fontSize(12)
//           .fillColor("#2563eb")
//           .text(file.documentName, { link: url, underline: true });

//         doc.fillColor("black");

//         if (url.includes("/image/upload/")) {
//           try {
//             const img = await axios.get(url, {
//               responseType: "arraybuffer",
//             });

//             doc.moveDown(0.5);
//             doc.image(Buffer.from(img.data), {
//               fit: [420, 250],
//               align: "center",
//             });
//           } catch {
//             doc.text("Image preview failed");
//           }
//         } else if (file.fileType === "application/pdf") {
//           doc.moveDown(0.5);
//           doc.fillColor("red").text("[PDF Document - Click to open]", {
//             link: url,
//           });
//           doc.fillColor("black");
//         } else {
//           doc.moveDown(0.5);
//           doc.text("📎 File - Click to open", { link: url });
//         }

//         doc.moveDown(1.5);
//       }

//       /* QR PAGE */
//       doc.addPage();

//       doc.fontSize(18).text("Verify Application", { align: "center" });
//       doc.moveDown();

//       const verifyUrl = `https://www.cadmaassociatespvtltd.com/verify/${app._id}`;
//       const qr = await QRCode.toDataURL(verifyUrl);

//       doc.image(qr, { fit: [200, 200], align: "center" });

//       doc.moveDown();
//       doc.fillColor("#2563eb").text(verifyUrl, {
//         align: "center",
//         link: verifyUrl,
//       });

//       doc.moveDown(2);
//       doc.fontSize(10).fillColor("gray").text(
//         "Generated by CADMA Associates Pvt Ltd System",
//         { align: "center" }
//       );

//       doc.end();
//     } catch (err) {
//       reject(err);
//     }
//   });
// }


import PDFDocument from "pdfkit";

export default function generatePDFBuffer(app) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });

    doc.fontSize(20).text("APPLICATION DETAILS", {
      align: "center",
    });

    doc.moveDown();

    doc.fontSize(12).text(`Name: ${app.userDetails.name}`);
    doc.text(`Email: ${app.userDetails.email}`);
    doc.text(`Phone: ${app.userDetails.phone}`);
    doc.text(`Service: ${app.serviceName}`);
    doc.text(`Status: ${app.status}`);

    doc.moveDown();
    doc.text("Documents:");

    app.uploadedDocuments.forEach((d) => {
      doc.text("• " + d.documentName);
    });

    doc.end();
  });
}
